name: Deploy Go Server to EC2

on:
  push:
    branches:
      - main   # or master, whichever you use

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.6   # ✅ use your required Go version

      - name: Debug repo structure
        run: ls -R

      - name: Build Go binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o server .

      - name: Stop old server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            lsof -t -i:8080 | xargs -r kill -9 || true
            rm -f /root/server

      - name: Upload new binary
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "server"
          target: "/root/"

      - name: Start server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: root
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            chmod +x /root/server
            nohup /root/server > /root/server.log 2>&1 &
